name: ðŸ“¦ Packing

on:
  release:
    types: [created, edited, published]
  workflow_dispatch:
env:
  TCR_URL: ccr.ccs.tencentyun.com
  NAME_SPACE: bite-dance

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build TCR image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{env.TCR_URL}}/${{env.NAME_SPACE}}/${{ github.event.repository.name }}
          tags: ${{ github.sha }}
          containerfiles: ./Dockerfile

      - name: Push To Tencent Cloud Registry
        id: push-to-tcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: $TCR_URL
          username: ${{secrets.TENCENT_REGISTRY_USERNAME}}
          password: ${{secrets.TENCENT_REGISTRY_PASSWORD}}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-tcr.outputs.registry-paths }}"
